version: '3.8'

services:
  app:
    build: .
    container_name: trip-planner-app
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=test
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
    depends_on:
      - db
    volumes:
      - ./app:/app

  db:
    image: postgres:13
    container_name: trip-planner-db
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 

# 数据卷
volumes:
  postgres_data: